version: '3.9'

services:
  bg-replace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  
      - PORT=${PORT}
    runtime: nvidia  
